/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as RequestCertificateRouteImport } from './routes/request-certificate'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FileBlotterRouteImport } from './routes/file-blotter'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminResidentsRouteImport } from './routes/admin.residents'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as AdminBlotterRouteImport } from './routes/admin.blotter'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestCertificateRoute = RequestCertificateRouteImport.update({
  id: '/request-certificate',
  path: '/request-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FileBlotterRoute = FileBlotterRouteImport.update({
  id: '/file-blotter',
  path: '/file-blotter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResidentsRoute = AdminResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlotterRoute = AdminBlotterRouteImport.update({
  id: '/blotter',
  path: '/blotter',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/file-blotter': typeof FileBlotterRoute
  '/login': typeof LoginRoute
  '/request-certificate': typeof RequestCertificateRoute
  '/track': typeof TrackRoute
  '/admin/blotter': typeof AdminBlotterRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/file-blotter': typeof FileBlotterRoute
  '/login': typeof LoginRoute
  '/request-certificate': typeof RequestCertificateRoute
  '/track': typeof TrackRoute
  '/admin/blotter': typeof AdminBlotterRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/file-blotter': typeof FileBlotterRoute
  '/login': typeof LoginRoute
  '/request-certificate': typeof RequestCertificateRoute
  '/track': typeof TrackRoute
  '/admin/blotter': typeof AdminBlotterRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/file-blotter'
    | '/login'
    | '/request-certificate'
    | '/track'
    | '/admin/blotter'
    | '/admin/certificates'
    | '/admin/residents'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/file-blotter'
    | '/login'
    | '/request-certificate'
    | '/track'
    | '/admin/blotter'
    | '/admin/certificates'
    | '/admin/residents'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/file-blotter'
    | '/login'
    | '/request-certificate'
    | '/track'
    | '/admin/blotter'
    | '/admin/certificates'
    | '/admin/residents'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FileBlotterRoute: typeof FileBlotterRoute
  LoginRoute: typeof LoginRoute
  RequestCertificateRoute: typeof RequestCertificateRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-certificate': {
      id: '/request-certificate'
      path: '/request-certificate'
      fullPath: '/request-certificate'
      preLoaderRoute: typeof RequestCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-blotter': {
      id: '/file-blotter'
      path: '/file-blotter'
      fullPath: '/file-blotter'
      preLoaderRoute: typeof FileBlotterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/residents': {
      id: '/admin/residents'
      path: '/residents'
      fullPath: '/admin/residents'
      preLoaderRoute: typeof AdminResidentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blotter': {
      id: '/admin/blotter'
      path: '/blotter'
      fullPath: '/admin/blotter'
      preLoaderRoute: typeof AdminBlotterRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlotterRoute: typeof AdminBlotterRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminResidentsRoute: typeof AdminResidentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlotterRoute: AdminBlotterRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminResidentsRoute: AdminResidentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FileBlotterRoute: FileBlotterRoute,
  LoginRoute: LoginRoute,
  RequestCertificateRoute: RequestCertificateRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
